import { Navigation } from "./components/navigation";
import "./styles/global.css";

export const metadata = {
  title: {
    template: "N-Admin | %s",
  },
  description: "Generated by SKT",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
